---

- name: generate
  hosts: localhost
  gather_facts:   false
  run_once:       true
  connection:     local
  tasks:
    - name:       generate vagrant.ssh_config
      raw:        'cd coreos;vagrant ssh-config > ../vagrant.ssh_config'
    - name:       download dynamic inventory source code
      get_url:
        url:      'https://raw.githubusercontent.com/ansible/ansible/devel/contrib/inventory/ssh_config.py'
        dest:     ./inventory.py
        mode:     0551
    - name:       replace ssh config file's path
      replace: 
        dest:     ./inventory.py
        regexp:   '~/\.ssh/config'
        replace:  './vagrant.ssh_config'
        backup:   no
